export interface Icd10SeedEntry {
  code: string;
  description: string;
}

// 220 ICD-10-CM codes spanning all major chapters — fictional demo data only
export const ICD10_SEED: Icd10SeedEntry[] = [
  // Chapter 1 — Infectious and parasitic diseases (A00–B99)
  { code: 'A00.0', description: 'Cholera due to Vibrio cholerae 01, biovar cholerae' },
  { code: 'A01.0', description: 'Typhoid fever' },
  { code: 'A02.0', description: 'Salmonella enteritis' },
  { code: 'A04.7', description: 'Enterocolitis due to Clostridium difficile' },
  { code: 'A09',   description: 'Other and unspecified gastroenteritis and colitis of infectious origin' },
  { code: 'A15.0', description: 'Tuberculosis of lung' },
  { code: 'A37.0', description: 'Whooping cough due to Bordetella pertussis' },
  { code: 'A40.3', description: 'Sepsis due to Streptococcus pneumoniae' },
  { code: 'A41.9', description: 'Sepsis, unspecified organism' },
  { code: 'A49.0', description: 'Staphylococcal infection, unspecified site' },
  { code: 'B00.1', description: 'Herpesviral vesicular dermatitis' },
  { code: 'B02.9', description: 'Zoster without complications' },
  { code: 'B07.9', description: 'Viral wart, unspecified' },
  { code: 'B18.2', description: 'Chronic viral hepatitis C' },
  { code: 'B20',   description: 'Human immunodeficiency virus [HIV] disease' },
  { code: 'B34.9', description: 'Viral infection, unspecified' },
  { code: 'B35.4', description: 'Tinea corporis' },
  { code: 'B37.0', description: 'Candidal stomatitis' },

  // Chapter 2 — Neoplasms (C00–D49)
  { code: 'C18.9', description: 'Malignant neoplasm of colon, unspecified' },
  { code: 'C34.10', description: 'Malignant neoplasm of upper lobe, bronchus or lung, unspecified side' },
  { code: 'C50.911', description: 'Malignant neoplasm of unspecified site of right female breast' },
  { code: 'C61',   description: 'Malignant neoplasm of prostate' },
  { code: 'C67.9', description: 'Malignant neoplasm of bladder, unspecified' },
  { code: 'C73',   description: 'Malignant neoplasm of thyroid gland' },
  { code: 'C80.1', description: 'Malignant (primary) neoplasm, unspecified' },
  { code: 'C85.10', description: 'Unspecified B-cell lymphoma, unspecified site' },
  { code: 'C90.00', description: 'Multiple myeloma not having achieved remission' },
  { code: 'C91.00', description: 'Acute lymphoblastic leukemia, not having achieved remission' },
  { code: 'D05.10', description: 'Intraductal carcinoma in situ of unspecified breast' },
  { code: 'D12.6', description: 'Benign neoplasm of colon, unspecified' },
  { code: 'D25.9', description: 'Leiomyoma of uterus, unspecified' },
  { code: 'D50.0', description: 'Iron deficiency anemia secondary to blood loss (chronic)' },
  { code: 'D64.9', description: 'Anemia, unspecified' },

  // Chapter 3 — Blood and blood-forming organs (D50–D89)
  { code: 'D68.9', description: 'Coagulation defect, unspecified' },
  { code: 'D69.3', description: 'Immune thrombocytopenic purpura' },
  { code: 'D70.9', description: 'Neutropenia, unspecified' },
  { code: 'D72.829', description: 'Elevated white blood cell count, unspecified' },
  { code: 'D89.9', description: 'Disorder involving the immune mechanism, unspecified' },

  // Chapter 4 — Endocrine, nutritional and metabolic diseases (E00–E89)
  { code: 'E03.9', description: 'Hypothyroidism, unspecified' },
  { code: 'E05.00', description: 'Thyrotoxicosis with diffuse goiter without thyrotoxic crisis' },
  { code: 'E06.3', description: 'Autoimmune thyroiditis' },
  { code: 'E10.9', description: 'Type 1 diabetes mellitus without complications' },
  { code: 'E11.65', description: 'Type 2 diabetes mellitus with hyperglycemia' },
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications' },
  { code: 'E13.40', description: 'Other specified diabetes mellitus with diabetic neuropathy, unspecified' },
  { code: 'E27.1', description: 'Primary adrenocortical insufficiency' },
  { code: 'E28.2', description: 'Polycystic ovarian syndrome' },
  { code: 'E55.9', description: 'Vitamin D deficiency, unspecified' },
  { code: 'E66.9', description: 'Obesity, unspecified' },
  { code: 'E78.5', description: 'Hyperlipidemia, unspecified' },
  { code: 'E83.52', description: 'Hypercalcemia' },
  { code: 'E87.1', description: 'Hypo-osmolality and hyponatremia' },
  { code: 'E87.5', description: 'Hyperkalemia' },

  // Chapter 5 — Mental and behavioural disorders (F01–F99)
  { code: 'F10.10', description: 'Alcohol abuse, uncomplicated' },
  { code: 'F17.210', description: 'Nicotine dependence, cigarettes, uncomplicated' },
  { code: 'F20.9', description: 'Schizophrenia, unspecified' },
  { code: 'F31.9', description: 'Bipolar disorder, unspecified' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified' },
  { code: 'F33.0', description: 'Major depressive disorder, recurrent, mild' },
  { code: 'F40.10', description: 'Social phobia, unspecified' },
  { code: 'F41.0', description: 'Panic disorder without agoraphobia' },
  { code: 'F41.1', description: 'Generalized anxiety disorder' },
  { code: 'F43.10', description: 'Post-traumatic stress disorder, unspecified' },
  { code: 'F50.00', description: 'Anorexia nervosa, unspecified' },
  { code: 'F60.3', description: 'Borderline personality disorder' },
  { code: 'F84.0', description: 'Autism spectrum disorder' },
  { code: 'F90.0', description: 'Attention-deficit hyperactivity disorder, predominantly inattentive type' },
  { code: 'F90.2', description: 'Attention-deficit hyperactivity disorder, combined type' },

  // Chapter 6 — Nervous system (G00–G99)
  { code: 'G20',   description: "Parkinson's disease" },
  { code: 'G25.0', description: 'Essential tremor' },
  { code: 'G30.0', description: "Alzheimer's disease with early onset" },
  { code: 'G35',   description: 'Multiple sclerosis' },
  { code: 'G40.909', description: 'Epilepsy, unspecified, not intractable, without status epilepticus' },
  { code: 'G43.909', description: 'Migraine, unspecified, not intractable, without status migrainosus' },
  { code: 'G45.9', description: 'Transient cerebral ischaemic attack, unspecified' },
  { code: 'G47.00', description: 'Insomnia, unspecified' },
  { code: 'G47.30', description: 'Sleep apnea, unspecified' },
  { code: 'G54.2', description: 'Cervical root disorders, not elsewhere classified' },
  { code: 'G62.9', description: 'Polyneuropathy, unspecified' },
  { code: 'G89.29', description: 'Other chronic pain' },

  // Chapter 7 — Eye and adnexa (H00–H59)
  { code: 'H10.9', description: 'Unspecified conjunctivitis' },
  { code: 'H25.9', description: 'Unspecified age-related cataract' },
  { code: 'H26.9', description: 'Unspecified cataract' },
  { code: 'H35.30', description: 'Unspecified macular degeneration' },
  { code: 'H40.10X0', description: 'Open-angle glaucoma, unspecified, stage unspecified' },
  { code: 'H52.4', description: 'Presbyopia' },

  // Chapter 8 — Ear and mastoid (H60–H95)
  { code: 'H61.20', description: 'Impacted cerumen, unspecified ear' },
  { code: 'H65.90', description: 'Unspecified nonsuppurative otitis media, unspecified ear' },
  { code: 'H66.90', description: 'Otitis media, unspecified, unspecified ear' },
  { code: 'H90.3', description: 'Sensorineural hearing loss, bilateral' },
  { code: 'H93.19', description: 'Tinnitus, unspecified ear' },

  // Chapter 9 — Circulatory system (I00–I99)
  { code: 'I10',   description: 'Essential (primary) hypertension' },
  { code: 'I11.0', description: 'Hypertensive heart disease with heart failure' },
  { code: 'I20.9', description: 'Angina pectoris, unspecified' },
  { code: 'I21.9', description: 'Acute myocardial infarction, unspecified' },
  { code: 'I25.10', description: 'Atherosclerotic heart disease of native coronary artery without angina pectoris' },
  { code: 'I35.0', description: 'Nonrheumatic aortic (valve) stenosis' },
  { code: 'I42.0', description: 'Dilated cardiomyopathy' },
  { code: 'I48.0', description: 'Paroxysmal atrial fibrillation' },
  { code: 'I48.91', description: 'Unspecified atrial fibrillation' },
  { code: 'I50.9', description: 'Heart failure, unspecified' },
  { code: 'I63.9', description: 'Cerebral infarction, unspecified' },
  { code: 'I73.9', description: 'Peripheral vascular disease, unspecified' },
  { code: 'I83.90', description: 'Varicose veins of unspecified lower extremity without ulcer or inflammation' },
  { code: 'I87.2', description: 'Venous insufficiency (chronic) (peripheral)' },

  // Chapter 10 — Respiratory system (J00–J99)
  { code: 'J00',   description: 'Acute nasopharyngitis [common cold]' },
  { code: 'J02.9', description: 'Acute pharyngitis, unspecified' },
  { code: 'J03.90', description: 'Acute tonsillitis, unspecified' },
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified' },
  { code: 'J18.9', description: 'Pneumonia, unspecified organism' },
  { code: 'J20.9', description: 'Acute bronchitis, unspecified' },
  { code: 'J30.9', description: 'Allergic rhinitis, unspecified' },
  { code: 'J32.9', description: 'Chronic sinusitis, unspecified' },
  { code: 'J45.20', description: 'Mild intermittent asthma, uncomplicated' },
  { code: 'J45.50', description: 'Severe persistent asthma, uncomplicated' },
  { code: 'J44.1', description: 'Chronic obstructive pulmonary disease with (acute) exacerbation' },
  { code: 'J44.9', description: 'Chronic obstructive pulmonary disease, unspecified' },
  { code: 'J68.0', description: 'Bronchitis and pneumonitis due to solids and liquids' },

  // Chapter 11 — Digestive system (K00–K95)
  { code: 'K21.0', description: 'Gastro-esophageal reflux disease with esophagitis' },
  { code: 'K25.9', description: 'Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation' },
  { code: 'K29.70', description: 'Gastritis, unspecified, without bleeding' },
  { code: 'K35.80', description: 'Other and unspecified acute appendicitis without abscess' },
  { code: 'K40.90', description: 'Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent' },
  { code: 'K51.90', description: 'Ulcerative colitis, unspecified, without complications' },
  { code: 'K57.30', description: 'Diverticulosis of large intestine without perforation or abscess without bleeding' },
  { code: 'K58.0', description: 'Irritable bowel syndrome with diarrhea' },
  { code: 'K70.30', description: 'Alcoholic cirrhosis of liver without ascites' },
  { code: 'K74.60', description: 'Unspecified cirrhosis of liver' },
  { code: 'K80.20', description: 'Calculus of gallbladder without cholecystitis without obstruction' },
  { code: 'K86.1', description: 'Other chronic pancreatitis' },
  { code: 'K92.1', description: 'Melena' },

  // Chapter 12 — Skin and subcutaneous tissue (L00–L99)
  { code: 'L01.00', description: 'Impetigo, unspecified' },
  { code: 'L02.01', description: 'Cutaneous abscess of face' },
  { code: 'L20.9', description: 'Atopic dermatitis, unspecified' },
  { code: 'L29.9', description: 'Pruritus, unspecified' },
  { code: 'L30.9', description: 'Dermatitis, unspecified' },
  { code: 'L40.0', description: 'Psoriasis vulgaris' },
  { code: 'L50.9', description: 'Urticaria, unspecified' },
  { code: 'L60.0', description: 'Ingrowing nail' },
  { code: 'L70.0', description: 'Acne vulgaris' },
  { code: 'L89.90', description: 'Pressure ulcer of unspecified site, unspecified stage' },

  // Chapter 13 — Musculoskeletal (M00–M99)
  { code: 'M05.79', description: 'Rheumatoid arthritis with rheumatoid factor of multiple sites without organ or systems involvement' },
  { code: 'M06.9', description: 'Rheumatoid arthritis, unspecified' },
  { code: 'M10.9', description: 'Gout, unspecified' },
  { code: 'M15.9', description: 'Polyosteoarthritis, unspecified' },
  { code: 'M17.11', description: 'Primary osteoarthritis, right knee' },
  { code: 'M19.90', description: 'Unspecified osteoarthritis, unspecified site' },
  { code: 'M25.511', description: 'Pain in right shoulder' },
  { code: 'M25.561', description: 'Pain in right knee' },
  { code: 'M32.9', description: 'Systemic lupus erythematosus, unspecified' },
  { code: 'M40.202', description: 'Unspecified kyphosis, cervical region' },
  { code: 'M47.816', description: 'Spondylosis without myelopathy or radiculopathy, lumbar region' },
  { code: 'M54.5', description: 'Low back pain' },
  { code: 'M54.2', description: 'Cervicalgia' },
  { code: 'M62.838', description: 'Muscle spasm of other site' },
  { code: 'M75.100', description: 'Unspecified rotator cuff tear or rupture of unspecified shoulder, not specified as traumatic' },
  { code: 'M79.3', description: 'Panniculitis, unspecified' },
  { code: 'M80.08XA', description: 'Age-related osteoporosis with current pathological fracture, vertebra(e), initial encounter' },
  { code: 'M81.0', description: 'Age-related osteoporosis without current pathological fracture' },

  // Chapter 14 — Genitourinary (N00–N99)
  { code: 'N10',   description: 'Acute pyelonephritis' },
  { code: 'N18.3', description: 'Chronic kidney disease, stage 3 (moderate)' },
  { code: 'N18.6', description: 'End stage renal disease' },
  { code: 'N20.0', description: 'Calculus of kidney' },
  { code: 'N39.0', description: 'Urinary tract infection, site not specified' },
  { code: 'N40.0', description: 'Benign prostatic hyperplasia without lower urinary tract symptoms' },
  { code: 'N43.3', description: 'Hydrocele, unspecified' },
  { code: 'N63.0', description: 'Unspecified lump in unspecified breast' },
  { code: 'N73.9', description: 'Female pelvic inflammatory disease, unspecified' },
  { code: 'N80.0', description: 'Endometriosis of uterus' },
  { code: 'N89.8', description: 'Other specified noninflammatory disorders of vagina' },
  { code: 'N92.0', description: 'Excessive and frequent menstruation with regular cycle' },
  { code: 'N95.1', description: 'Menopausal and female climacteric states' },

  // Chapter 15 — Pregnancy, childbirth (O00–O9A)
  { code: 'O09.90', description: 'Supervision of high risk pregnancy, unspecified, unspecified trimester' },
  { code: 'O10.011', description: 'Pre-existing essential hypertension complicating pregnancy, first trimester' },
  { code: 'O26.891', description: 'Other specified pregnancy related conditions, first trimester' },
  { code: 'O80',   description: 'Encounter for full-term uncomplicated delivery' },

  // Chapter 16 — Perinatal (P00–P96)
  { code: 'P07.30', description: 'Preterm newborn, unspecified weeks of gestation' },
  { code: 'P22.0', description: 'Respiratory distress syndrome of newborn' },
  { code: 'P59.9', description: 'Neonatal jaundice, unspecified' },

  // Chapter 17 — Congenital (Q00–Q99)
  { code: 'Q21.0', description: 'Ventricular septal defect' },
  { code: 'Q21.1', description: 'Atrial septal defect' },
  { code: 'Q35.9', description: 'Cleft palate, unspecified' },
  { code: 'Q65.9', description: 'Congenital deformity of hip, unspecified' },

  // Chapter 18 — Symptoms and signs (R00–R99)
  { code: 'R00.0', description: 'Tachycardia, unspecified' },
  { code: 'R00.1', description: 'Bradycardia, unspecified' },
  { code: 'R05.9', description: 'Cough, unspecified' },
  { code: 'R06.00', description: 'Dyspnea, unspecified' },
  { code: 'R07.9', description: 'Chest pain, unspecified' },
  { code: 'R10.9', description: 'Unspecified abdominal pain' },
  { code: 'R11.0', description: 'Nausea alone' },
  { code: 'R11.2', description: 'Nausea with vomiting, unspecified' },
  { code: 'R19.7', description: 'Diarrhea, unspecified' },
  { code: 'R20.2', description: 'Paraesthesia of skin' },
  { code: 'R25.2', description: 'Cramp and spasm' },
  { code: 'R41.3', description: 'Other amnesia' },
  { code: 'R42',   description: 'Dizziness and giddiness' },
  { code: 'R50.9', description: 'Fever, unspecified' },
  { code: 'R51.9', description: 'Headache, unspecified' },
  { code: 'R53.83', description: 'Other fatigue' },
  { code: 'R55',   description: 'Syncope and collapse' },
  { code: 'R60.0', description: 'Localized edema' },
  { code: 'R63.0', description: 'Anorexia' },
  { code: 'R68.89', description: 'Other specified general symptoms and signs' },
  { code: 'R73.09', description: 'Other abnormal glucose' },

  // Chapter 19 — Injury and poisoning (S00–T88)
  { code: 'S00.01XA', description: 'Unspecified superficial injury of scalp, initial encounter' },
  { code: 'S09.90XA', description: 'Unspecified injury of head, initial encounter' },
  { code: 'S22.009A', description: 'Fracture of unspecified thoracic vertebra, initial encounter for closed fracture' },
  { code: 'S42.001A', description: 'Fracture of unspecified part of clavicle, right side, initial encounter for closed fracture' },
  { code: 'S52.509A', description: 'Unspecified fracture of the lower end of unspecified radius, initial encounter for closed fracture' },
  { code: 'S62.309A', description: 'Fracture of unspecified metacarpal bone, initial encounter for closed fracture' },
  { code: 'S82.009A', description: 'Fracture of unspecified part of neck of unspecified femur, initial encounter for closed fracture' },
  { code: 'S93.401A', description: 'Sprain of unspecified ligament of right ankle, initial encounter' },
  { code: 'T14.90XA', description: 'Injury, unspecified, initial encounter' },
  { code: 'T36.0X5A', description: 'Adverse effect of penicillins, initial encounter' },
  { code: 'T45.515A', description: 'Adverse effect of anticoagulants, initial encounter' },
  { code: 'T78.40XA', description: 'Allergy, unspecified, initial encounter' },

  // Chapter 20 — External causes (V00–Y99)
  { code: 'V49.9XXA', description: 'Car occupant injured in unspecified traffic accident, initial encounter' },
  { code: 'W19.XXXA', description: 'Unspecified fall, initial encounter' },

  // Chapter 21 — Factors influencing health status (Z00–Z99)
  { code: 'Z00.00', description: 'Encounter for general adult medical examination without abnormal findings' },
  { code: 'Z00.121', description: 'Encounter for routine child health examination with abnormal findings' },
  { code: 'Z01.01', description: 'Encounter for examination of eyes and vision with abnormal findings' },
  { code: 'Z12.11', description: 'Encounter for screening for malignant neoplasm of colon' },
  { code: 'Z12.31', description: 'Encounter for screening mammogram for malignant neoplasm of breast' },
  { code: 'Z13.1', description: 'Encounter for screening for diabetes mellitus' },
  { code: 'Z23',   description: 'Encounter for immunization' },
  { code: 'Z30.09', description: 'Encounter for other general counseling and advice on contraception' },
  { code: 'Z34.00', description: 'Encounter for supervision of normal first pregnancy, unspecified trimester' },
  { code: 'Z51.11', description: 'Encounter for antineoplastic chemotherapy' },
  { code: 'Z71.89', description: 'Encounter for other specified counseling' },
  { code: 'Z79.01', description: 'Long-term (current) use of anticoagulants' },
  { code: 'Z79.4', description: 'Long-term (current) use of insulin' },
  { code: 'Z82.49', description: 'Family history of ischemic heart disease and other diseases of the circulatory system' },
  { code: 'Z87.39', description: 'Personal history of other musculoskeletal disorders' },
  { code: 'Z96.641', description: 'Presence of right artificial knee joint' },
];
